name: DevOps CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Build backend Docker image
      - name: Build backend Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devops-backend:1.0 ./backend

      # 4. Build frontend Docker image
      - name: Build frontend Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devops-frontend:2.3 ./frontend

      # 5. Scan backend image with Trivy
      - name: Run Trivy vulnerability scanner - Backend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ secrets.DOCKERHUB_USERNAME }}/devops-backend:1.0"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"

      # 6. Scan frontend image with Trivy
      - name: Run Trivy vulnerability scanner - Frontend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ secrets.DOCKERHUB_USERNAME }}/devops-frontend:2.3"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"

      # 7. SonarQube code analysis
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # 8. Push backend image to Docker Hub
      - name: Push backend image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-backend:1.0

      # 9. Push frontend image to Docker Hub
      - name: Push frontend image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-frontend:2.3

