name: DevOps CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build backend Docker image
        run: docker build -t devops-backend:1.0 ./backend

      - name: Build frontend Docker image
        run: docker build -t devops-frontend:1.1 ./frontend
